### ISSUE TITLE
Subpaths with URI parameters are created as list items without a newline.

### ISSUE THREAD

**Issue by armyofevilrobots** [OpusCapita/raml-to-markdown#10]
When list items are generated as part of a list of URIs which are subpaths, they end up on the same line instead of sequential, ie, when rendering:

```yaml
/clusters:
  get:
  post:
  /{cluster_id}:
    get:
    put:
```
You'll end up with this:

* [/clusters](#clusters) * [/clusters/{cluster_id}](#clusterscluster_id)

instead of
* [/clusters](#clusters)
* [/clusters/{cluster_id}](#clusterscluster_id)
